// the bindings generated by build.rs don't follow Rust's style conventions...
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
include!(concat!(env!("OUT_DIR"), "/objectbox-c-bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    /// verify the installed library version is the same as the version from objectbox.h
    #[test]
    fn check_version() {
        let mut major: i32 = 0;
        let mut minor: i32 = 0;
        let mut patch: i32 = 0;

        unsafe { obx_version(&mut major, &mut minor, &mut patch) }

        println!("ObjectBox version {}.{}.{} loaded ", major, minor, patch);

        assert_eq!(major, OBX_VERSION_MAJOR as i32);
        assert_eq!(minor, OBX_VERSION_MINOR as i32);
        assert_eq!(patch, OBX_VERSION_PATCH as i32);
    }
}
